[package]
name = "hubrate"
version = "0.1.0"
authors = ["Dale Wijnand <dale.wijnand@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
hubcaps = "0.5.0"
pretty_env_logger = "0.3.0"
tokio = "0.1.13"
